export const questions = [
  {
    id: 1,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'Previdência',
    question: 'A definição de natureza da lesão, segundo a NBR 14.280, é',
    alternatives: [
      '(A)Qualquer dano sofrido pelo organismo humano, como consequência de acidente do trabalho.',
      '(B)Expressão que identifica a lesão, segundo suas características principais.',
      '(C)Indicação da sede da lesão.',
      '(D)Lesão que se manifesta no momento do acidente.',
      '(E)Lesão que não se manifesta imediatamente após a circunstância acidental da qual resultou.',
    ],
    answer: 'B',
    tip: 'Texto da própia NBR',
  },
  {
    id: 2,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR23',
    question:
      'Associe o tipo de extintor de incêndio (numerados na coluna da direita) à classe de fogo (na coluna da esquerda) na qual ele deve ser utilizado, segundo determina a NR-23. \nClasse de fogo   |   Tipo de extintor \n   A      |      I- Espuma \n   B      |      II-Dióxido de Carbono \n   C      |      III-Químico Seco \n   D      |      IV- Água pressurizada ou Água-Gás \n Assinale a alternativa que apresente somente associações corretas.',
    alternatives: [
      '(A)A-I/B-II/C-IV',
      '(B)A-IV/B-III/C-II',
      '(C)A-II/B-I/D-IV',
      '(D)A-III/B-II/C-I',
      '(E)A-IV/B-III/D-II',
    ],
    answer: 'B',
    tip: 'Classe A = Materiais combustíveis sólidos (Extintor mais recomendado Água Pressurizada-AP pois resfria e abafa), \n Classe B = Materiais combustíveis líquidos (Extintor mais recomendado Espuma pois abafa o fogo fazendo uma camada entre o líquido e o ar), \n Classe C = Ignição elétrica (Extintor mais recomendado é o de CO2 pois retira o comburuente/oxigênio sem muitos danos aos equipamentos), \n Classe D = Metais Pirofóricos (Extintor mais recomendado é o de pó químico).',
  },
  {
    id: 3,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR9',
    question:
      'Em relação às técnicas de Análise de Riscos, analise as afirmativas a seguir: \n    I. APR é uma técnica que identifica os cenários acidentais possíveis e determina o risco desses cenários quantitativamente. \n        II.   O HAZOP é uma técnica que só pode ser aplicada em sistemas de operação em bateladas, avaliando qualitativamente o risco do sistema em estudo. \n        III.   Utilizando a técnica FMEA, determinam-se os modos de falhas de componentes de um sistema operacional e seus efeitos em outros componentes e no sistema, podendo ser de forma quantitativa. \n        IV.  A metodologia Análise por Árvore de Falhas avalia de forma qualitativa e quantitativa o risco de um determinado cenário ocorrer e auxilia a identificar as combinações de falhas humanas e de componentes. \n        Assinale',
    alternatives: [
      '(A)Se apenas as afirmativas I e II forem corretas.',
      '(B)Se apenas as afirmativas III e IV forem corretas.',
      '(C)Se apenas as afirmativas I e IV forem corretas.',
      '(D)Se apenas as afirmativas II e IV forem corretas.',
      '(E)Se apenas as afirmativas I e III forem corretas.',
    ],
    answer: 'B',
    tip: 'A APR é qualitativa e a HAZOP trás análises quantitativas.',
  },
  {
    id: 4,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR23',
    question:
      'O fenômeno conhecido como Boilover pode ser mais bem definido quando',
    alternatives: [
      '(A) o gás liquefeito, por pressurização, é liberado repentinamente entrando em ignição imediatamente. ',
      '(B) há liberação de líquido inflamável com posterior ignição.',
      '(C) a velocidade de queima de uma nuvem inflamável é muito baixa.',
      '(D) ocorre uma explosão devido à evaporação súbita da água residual em tanques de petróleo após incêndio prolongado. ',
      '(E) ocorre uma explosão por expansão do Vapor Líquido Fervente.',
    ],
    answer: 'D',
    tip: 'O Boilover é o principal motivo por não poder se apagar incêndio de classe B(combustíveis líquidos) com água, ou líquidos mais densos que o produto inflamável.\n Por ser mais pesada, a água se acomoda no fundo do reservatório sem apagar o fogo. O aquecimento e a pressão sobre a água confinada abaixo do líquido inflamável faz com que ela possa causar explosões ainda mais graves.',
  },
  {
    id: 5,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR15',
    question:
      'Considere as afirmativas abaixo: \n I.A dose média de radiação natural absorvida pela população mundial é  de 2,6 Gy x 10^3 x ano^-1, isto é, 2,6 mGy por ano. \n II. Radiação gama é do tipo partículas. \nIII. Radiação alfa do tipo eletromagnética. \n IV. Radiação nucleares do tipo partículas possuem massa, carga elétrica e velocidade, esta dependente do valor de sua energia. \n V.Ondas eletromagnéticas não possuem massa e se propagam com a velocidade 300.000 km/s, para qualquer valor de sua energia. \n Assinale',
    alternatives: [
      '(A) Se apenas as afirmativas I, II e IV forem corretas.',
      '(B) Se apenas as afirmativas I, III e IV forem corretas.',
      '(C) Se apenas as afirmativas II, IV e V forem corretas.',
      '(D) Se apenas as afirmativas II, III e IV forem corretas.',
      '(E) Se apenas as afirmativas I, IV e V forem corretas.',
    ],
    answer: 'E',
    tip: ' Radiação Alfa é do tipo partículas oriundo do decaimento radioativo de um núcleo atômico instável; \n Radiação Gama é do tipo eletromagnética de alta frequência.',
  },
  {
    id: 6,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR15',
    question:
      'Um radioisótopo tem meia-vida de 200 dias. Após quantos dias o radioisótopo terá decaído a valores correspondentes a 12,5% da sua atividade inicial?',
    alternatives: [
      '(A) 50 dias.',
      '(B) 225 dias.',
      '(C) 375 dias.',
      '(D) 400 dias.',
      '(E) 600 dias.',
    ],
    answer: 'E',
    tip: ' 200 dias = 50 % da vida \n400 dias = 50% de 50% da vida = 25% \n600 dias = 50% de 25% da vida = 15,5% ',
  },
  {
    id: 7,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'Análise de riscos',
    question:
      'Após a ocorrência de um acidente, uma análise deve ser iniciada o mais rapidamente possível para determinar todas as causa e recomendar ações de melhoria, que, quando implementadas, poderão evitar reincidências e consequentemente mais perdas. A técnica de investigação de acidentes que consiste em determinar as causas mais distantes (básicas) pela pergunta "o que levou a...?" é denominada',
    alternatives: [
      '(A) AMFE – Análise dos Modos de Falhas e Efeitos.',
      '(B) HAZOP – Hazard Operability Studies.',
      '(C) AST – Análise de Segurança da Tarefa.',
      '(D) AAC – Análise por Árvore de Causas.',
      '(E) APP – Análise Preliminar de Perigos.',
    ],
    answer: 'D',
    tip: '',
  },
  {
    id: 8,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR33',
    question:
      'Os procedimentos de entrada em espaços confinados devem ser revistos quando da ocorrência de qualquer uma das circunstâncias abaixo: \n    I. entrada não autorizada num espaço confinado; \n    II. quando houver uma razão para acreditar que existam desvios na utilização ou nos procedimentos de entrada nos espaços confinados ou que os conhecimentos não sejam adequados; \n    III. identificação de riscos não descritos na Permissão de Entrada de Trabalho; \n    IV. mudança nos procedimentos, condições ou operações de trabalho; \n    V. acidente, incidente ou condição não prevista durante a entrada; \n    VI. qualquer mudança na atividade desenvolvida ou na configuração do espaço confinado. \n    Analise os itens acima e assinale',
    alternatives: [
      '(A) Se apenas as afirmativas I, II e IV forem corretas.',
      '(B) Se apenas as afirmativas I, III e IV forem corretas.',
      '(C) Se apenas as afirmativas II, IV e V forem corretas.',
      '(D) Se apenas as afirmativas II, III e IV forem corretas.',
      '(E) Se apenas as afirmativas I, IV e V forem corretas.',
    ],
    answer: 'E',
    tip: 'NR33\n alínea 33.3.3.5 "Os procedimentos de entrada em espaços confinados devem ser revistos quando da ocorrência de qualquer uma das circunstâncias abaixo:\n a) entrada não autorizada num espaço confinado;\n b) identificação de riscos não descritos na Permissão de Entrada e Trabalho;\n c) acidente, incidente ou condição não prevista durante a entrada;\n d) qualquer mudança na atividade desenvolvida ou na configuração do espaço confinado;\n e) solicitação do SESMT ou da CIPA;\n e f) identificação de condição de trabalho mais segura."',
  },
  {
    id: 9,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR26',
    question:
      'Segundo a NR26 (Sinalização de Segurança), canalizações que contenham inflamáveis e combustíveis de baixa viscosidade e ácidos devem ser pintadas, respectivamente, nas cores',
    alternatives: [
      '(A) lilás e laranja.',
      '(B) laranja e alumínio.',
      '(C) lilás e alumínio.',
      '(D) laranja e cinza-claro.',
      '(E) lilás e cinza-claro.',
    ],
    answer: 'B',
    tip: ' Para decoreba: \n Amarelo = Gases não liquefeitos, avisos de cuidado e corrimão;\n Alumínio = Inflamáveis de baixa viscosidade;\n Preto = Inflamáveis de alta viscosidade;\n Azul = Bandeiras e cuidados em máquinas;\n Branco = Corredor/Passagens;\n Cinza Claro = Vácuo;\n Cinza Escuro = eletrodutos;\n Púrpura = eletromagnetismo e radiações;\n  Laranja = ácidos, engrenagens perigosas e faces interiores de máquinas;\n Lilás = Alcális;\n Marrom = a critério da empresa;\n Verde = Segurança e kits de primeiros socorros',
  },
  {
    id: 10,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR33',
    question:
      'Uma perda de 1,2% do teor de oxigênio em um espeço confinado pode significar que houve uma entrada de outro gás contaminante nesse ambiente. A quantidade desse contaminante pode ser no mínimo, igual a',
    alternatives: [
      '(A) 4,8%.',
      '(B) 1,2%.',
      '(C) 2,4%.',
      '(D) 6,0%.',
      '(E) 7,2%.',
    ],
    answer: 'D',
    tip: '',
  },
  {
    id: 11,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR35',
    question:
      'Assinale a altura da queda livre de um trabalhador situado em uma plataforma elevada, utilizando cinto de segurança, considerando que: \n - o anel D do cinto de segurança (as suas costas) está a 1,5m de distância (altura) do piso da plataforma; \n - o ponto de ancoramento do cinto está situado no piso da plataforma; \n- o comprimento do talabarte é de 1,20m e o estiramento do amortecedor é igual ao seu comprimento; \n- o estiramento do anel D é de 0,30m; e  \nO fator de segurança é de 0,60m.',
    alternatives: [
      '(A) 4,3 metros.',
      '(B) 2,2 metros.',
      '(C) 2,8 metros.',
      '(D) 3,6 metros.',
      '(E) 4,8 metros.',
    ],
    answer: 'E',
    tip: 'Como o ponto de ancoragem está localizado no piso do trabalhador, o trabalhador está trabalhando com um fator de queda(FQ) igual a 2.\n Ou seja, o tabalabarte só irá reter a sua queda quando o trabalhador cair uma altura de duas vezes o tamanho do talabarte.\n Primeiro, ele caíra uma distância até o piso (dist. de um talabarte) sem que o talabarte o proteja. Depois, ele caíra a distância do próprio comprimento do talabarte até que ele segure a queda.\n Portando, a altura de queda livre será:\n 1,5 + 2x1,20(Comprimento talabarte vezes 2) + 0,3 + 0,6 = 4,8m',
  },
  {
    id: 12,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR18',
    question:
      'A proteção contra quedas, segundo a NR-18,quando constituída de anteparos rígidos, em sistema de guarda-corpo e rodapé, deve ser construída com altura de',
    alternatives: [
      '(A) 1,20m para o travessão superior e 0,70m para o travessão intermediário.',
      '(B) 1,50m para o travessão superior e 0,70m para o travessão intermediário.',
      '(C) 1,20m para o travessão superior e 0,60m para o travessão intermediário.',
      '(D) 1,50m para o travessão superior e 0,60m para o travessão intermediário.',
      '(E) 1,50m para o travessão superior e 0,70m para o travessão intermediário.',
    ],
    answer: 'A',
    tip: 'Item 18.1 3.5 da NR18(2021)',
  },
  {
    id: 13,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR23',
    question:
      'Considerando a densidade relativa dos gases e vapores em relação ao ar, analise as afirmativas a seguir: \nI. O acetileno é menos denso que o ar. \nII. O CO é mais denso que o ar. \nIII. O CO2 é menos denso que o ar. \nIV. O H2 é mais denso que o ar. \nEstão INCORRETAS',
    alternatives: [
      '(A) apenas as afirmativas I,II e III.',
      '(B) apenas as afirmativas II, III e IV.',
      '(C) apenas as afirmativas I,III e IV.',
      '(D) apenas as afirmativas I,II e IV.',
      '(E) todas as afirmativas.',
    ],
    answer: 'B',
    tip: 'Para verificar esta questão, basta verificar a densidade relativa de cada gás e vapor em suas respectivas FISPQ. A densidade relativa tem este nome pois ela é feita em comparação com ar natural, ou seja, ela é "relativa" ao ar natural. Neste contexto, o ar natural será sua densidade relativa sempre igual a 1. Logo, qualquer gás/vapor com densidade menor que 1, será mais leve que o ar e qualquer gás/vapor com densidade maior que 1, será mais pesado que o ar.\n Pelas FISPQ:\n I - Dr(acetileno)=0,91 - (< 1 - menos denso) CORRETA!\n Dr(CO)=0,97 (< 1 - menos denso) INCORRETA\n Dr(CO2)=1,53 (> 1 - mais denso) INCORRETA\n Dr(H2)= 0,067 (<< 1 - muito menos denso) INCORRETA \n fontes: https://cloud.cnpgc.embrapa.br/wp-content/igu/fispq/laboratorios/acetileno-produquimica.pdf\n https://licenciamento.cetesb.sp.gov.br/produtos/ficha_completa1.asp?consulta=MON%D3XIDO%20DE%20CARBONO,%20COMPRIMIDO\n https://sites.ffclrp.usp.br/cipa/fispq/Hidrogenio.pdf',
  },
  {
    id: 14,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR23',
    question:
      'A Norma Brasileira adota, para designar o grau de risco de áreas classificadas, o termo zona. \nA esse respeito assinale a alternativa correta.',
    alternatives: [
      '(A) Zona 0: local onde a existência de mistura inflamável/ explosiva é pouco provável de acontecer',
      '(B) Zona 1: local onde a ocorrência de mistura inflamável/explosiva é contínua.',
      '(C) Zona 2: local onde a ocorrência de mistura inflamável/explosiva é contínua.',
      '(D) Zona 21:  áreas onde a presença de atmosfera explosiva devido ao levantamento de poeira pode ocorrer ocasionalmente. ',
      '(E)  Zona 20:  áreas onde a presença de atmosfera explosiva devido ao levantamento de poeira é improvável, se ocorrer é por pouco tempo.',
    ],
    answer: 'D',
    tip: ' Zonas para Gases e  Vapores ( de 0 a 2) \n Zona 0: Áreas onde a presença da atmosfera explosiva é permanente ou por tempo prolongado. \nZona 1: Áreas onde a presença da atmosfera explosiva é provável em operação normal. \nZona 2:  Áreas onde a presença da atmosfera explosiva em operação normal é improvável, se ocorrer é por pouco tempo. \nZonas para Poeiras ( de 20 a 22) \nZona 20: Áreas onde a presença da atmosfera explosiva é permanente ou por tempo prolongado, ou frequente. \nZona 21: Áreas onde a presença da atmosfera explosiva pode ocorrer ocasionalmente. \nZona 22:  Áreas onde a presença da atmosfera explosiva devido ao levantamento de poeira acumulada é improvável, se ocorrer é por pouco tempo. \n \nFonte: http://www.inmetro.gov.br/painelsetorial/palestras/Seguran%C3%A7aR%C3%B6pker.pdf',
  },
  {
    id: 15,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR10',
    question:
      'Um equipamento intrinsecamente seguro que tem a especificação CL1, DIV 1: GP C, D na sua etiqueta de identificação significa que não deve ser utilizado em áreas contendo os seguintes gases:',
    alternatives: [
      '(A) etileno equivalente.',
      '(B) acetona e amônia.',
      '(C) hidrogênio ou equivalente.',
      '(D) gás natural ou equivalente.',
      '(E) gasolina e propano.',
    ],
    answer: 'C',
    tip: '',
  },
  {
    id: 16,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR10',
    question:
      'Diante de uma vítima de choque elétrico consciente, como devemos proceder?',
    alternatives: [
      '(A) Deitá-la de costas com as pernas levantadas.',
      '(B) Aplicar adrenalina.',
      '(C) Verificar o pulso carotídeo.',
      '(D) Colocá-la em prancha rígida.',
      '(E) Deixá-la em posição confortável, mantendo-a calmo, aquecida e com as roupas afrouxadas.',
    ],
    answer: 'A',
    tip: '',
  },
  {
    id: 17,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR15',
    question:
      'Um solvente orgânico pode penetrar no organismo principalmente por via',
    alternatives: [
      '(A) oral e respiratória.',
      '(B) respiratória e cutânea.',
      '(C) oral e cutânea.',
      '(D) ocular e oral.',
      '(E) ocular e respiratória.',
    ],
    answer: 'B',
    tip: '',
  },
  {
    id: 18,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR17',
    question:
      'Que norma da ABNT – Associação Brasileira de Normas Técnicas deve ser respeitada quanto às curvas NC, para níveis de ruído aceitáveis (conforto acústico) em áreas administrativas?',
    alternatives: [
      '(A) NBR-10155.',
      '(B) NBR-10512.',
      '(C) NBR-10152.',
      '(D) NBR-10151.',
      '(E) NBR-10511.',
    ],
    answer: 'C',
    tip: 'NR17 item 17.5.2. Nos locais de trabalho onde são executadas atividades que exijam solicitação intelectual e atenção constantes, tais como: salas de controle, laboratórios, escritórios, salas de desenvolvimento ou análise de projetos, dentre outros, são recomendadas as seguintes condiçôes de conforto: \n a) níveis de ruído de acordo com o estabelecido na NBR 10152, norma brasileira registrada no INMETRO; (117.023-6 / I2)',
  },
  {
    id: 19,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR15',
    question:
      'Tendo como base o disposto na NR-15 e que um trabalhador tem uma jornada de 8 horas por dia, qual é o nível de ação para o agente ruído?',
    alternatives: [
      '(A) 80 dB(A).',
      '(B) 42,5 dB(A).',
      '(C) 40 dB(A).',
      '(D) 50 dB(A).',
      '(E) 82 dB(A).',
    ],
    answer: 'A',
    tip: 'Nível de ação é equivalente à metade do limite de tolerância. Como as doses de ruído decaem pela metade à cada 5 dB(A). O nível de ação para o ruído é de 80 dB(A).',
  },
  {
    id: 20,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR9',
    question:
      'Do ponto de vista da Higiene Ocupacional, Monitoramento Ambiental é',
    alternatives: [
      '(A) avaliação das concentrações no ar utilizando monitores passivos.',
      '(B) o mesmo que avaliação ambiental.',
      '(C) avaliação sistemática e repetitiva da exposição ocupacional.',
      '(D) realizar avaliação de todos os grupos homogêneos de um PPRA.',
      '(E) medição de agentes físicos e químicos',
    ],
    answer: 'C',
    tip: '',
  },
  {
    id: 21,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'Análise de riscos',
    question:
      'Um cenário retirado de uma APR – Análise Preliminar de Riscos é composto por',
    alternatives: [
      '(A) Causa, Consequência e Risco.',
      '(B) Perigo, Causa e Risco.',
      '(C) Perigo, Causa e Consequência.',
      '(D) Causa, Consequência Frequência e Severidade.',
      '(E) Perigo, Consequência e Risco.',
    ],
    answer: 'C',
    tip: '',
  },
  {
    id: 22,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'CODESP',
    year: 2010,
    subject: 'NR15',
    question:
      'Para fazer uma boa barreira para radiofrequência de um micro-ondas,',
    alternatives: [
      '(A) usa-se uma parede sólida de alvenaria.',
      '(B) usa-se vidro, como no forno de micro-ondas.',
      '(C) usam-se chapas ou telas metálicas.',
      '(D) usa-se uma proteção com madeira.',
      '(E)não há necessidade de barreira, pois o próprio micro-ondas já possui barreira suficiente.',
    ],
    answer: 'C',
    tip: '',
  },
  {
    id: 23,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR9',
    question:
      ' A respeito do processo de análise de riscos, analise as afirmativas a seguir.\nI. A avaliação de risco é um processo científico para prever o risco em um sistema.\nII. A percepção de falha no sistema depende do conhecimento sobre o sistema e das características cognitivas do indivíduo.\nIII. A comunicação do risco é um processo interativo de troca de informações entre as pessoas, de modo a transmitir as mensagens de risco.\nEstá correto o que se afirma em',
    alternatives: [
      '(A) I, somente.',
      '(B) II, somente.',
      '(C) III, somente.',
      '(D) II e III, somente.',
      '(E) I, II e III.',
    ],
    answer: 'A',
    tip: '',
  },
  {
    id: 24,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR4',
    question:
      'O Serviço Especializado em Engenharia de Segurança e Medicina do Trabalho – SESMT, de acordo com a NR-4, deve ser avaliado em períodos de',
    alternatives: [
      '(A) três meses.',
      '(B) seis meses.',
      '(C) nove meses.',
      '(D) doze meses.',
      '(E) dezoito meses.',
    ],
    answer: 'B',
    tip: 'NR 4- item - 4.5.3.3 O SESMT organizado conforme o subitem 4.5.3 deve ter seu funcionamento avaliado semestralmente, por Comissão composta de representantes da empresa contratante, do sindicato de trabalhadores e da Delegacia Regional do Trabalho, ou na forma e periodicidade previstas na Convenção ou Acordo Coletivo de Trabalho. (Subitem 4.5.3 aprovado pela Portaria SST 17/2007).',
  },
  {
    id: 25,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'Análise de riscos',
    question:
      'Após a ocorrência de um evento potencialmente capaz de provocar um acidente, mas que não se configurou, deve-se ter como ação',
    alternatives: [
      '(A) registrar o evento.',
      '(B) reciclar o trabalhador envolvido.',
      '(C) chamar a atenção dos trabalhadores para o evento.',
      '(D) verificar se existe o registro de um evento semelhante.',
      '(E) investigar o evento como se tivesse ocorrido o acidente.',
    ],
    answer: 'E',
    tip: '',
  },
  {
    id: 26,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'Análise de riscos',
    question:
      'O acidente do trabalho pode ter várias causas que devem ser investigadas. Assinale a opção que apresenta uma condição insegura.',
    alternatives: [
      '(A) Falta de EPI.',
      '(B) Falta de supervisão.',
      '(C) Excesso de confiança.',
      '(D) Preocupação alheias ao trabalho.',
      '(E) Indiferença às questões da segurança.',
    ],
    answer: 'A',
    tip: '',
  },
  {
    id: 27,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'Geral',
    question:
      'Na elaboração de uma Norma Técnica, deve-se buscar procedimentos acessíveis que garantam sua rapidez e a qualidade no desenvolvimento. Esse procedimento caracteriza o princípio de',
    alternatives: [
      '(A) Consenso.',
      '(B) Simplificação.',
      '(C) Comunicação.',
      '(D) Transparência.',
      '(E) Eliminação de Barreiras.',
    ],
    answer: 'B',
    tip: '',
  },
  {
    id: 28,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'Análise de riscos',
    question:
      'Um acidente de trabalho pode ocorrer em decorrência de falhas humanas ou de um meio inadequado de trabalho.\n A esse respeito, considere as afirmativas a seguir.\n I. O equipamento de proteção coletiva é um fator que contribui para a diminuição de atos inseguros.\n II. A política salarial de uma empresa pode motivar um ato inseguro.\n III. O ato inseguro é definido como sendo a execução de tarefas de forma contrária às normas de segurança.\n Está correto o que se afirma em',
    alternatives: [
      '(A) I, somente.',
      '(B) II, somente.',
      '(C) I e II, somente.',
      '(D) I e III, somente.',
      '(E) II e III, somente.',
    ],
    answer: 'E',
    tip: '',
  },
  {
    id: 29,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR17',
    question:
      'A ergonomia é a ciência que estuda a melhor adaptação do trabalho às características fisiológicas e psicológicas do ser humano. A respeito dos estudos ergonômicos, assinale a afirmativa correta.',
    alternatives: [
      '(A) Devem ser realizados, pelo menos, semestralmente.',
      '(B) Devem considerar as questões econômicas da empresa.',
      '(C) Tem como objetivo a diminuição das doenças decorrentes do trabalho.',
      '(D) Estabelece que a alocação do trabalhador deve respeitar o seu perfil psicofisiológico.',
      '(E) Visa ao aumento da produtividade pela melhor adequação psicofisiológica do trabalhador.',
    ],
    answer: 'C',
    tip: '',
  },
  {
    id: 30,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR12',
    question:
      'A Norma Regulamentadora 12 define as medidas de proteção que visam garantir a saúde e a integridade física dos trabalhadores na utilização de máquinas e equipamentos.\n Assinale a opção que apresenta as medidas de proteção em ordem prioritária, da maior para a de menor prioridade.',
    alternatives: [
      '(A) Proteção individual, administrativas e proteção coletiva.',
      '(B) Proteção Individual, proteção coletiva e administrativas.',
      '(C) Proteção coletiva, administrativas e proteção individual.',
      '(D) Organizacional do trabalho, proteção individual e proteção coletiva.',
      '(E) Proteção coletiva, proteção individual e organizacional do trabalho.',
    ],
    answer: 'C',
    tip: 'A questão continua atualizada mesmo com a atualização da NR12 em 2019.',
  },
  {
    id: 31,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'Previdência',
    question:
      'A respeito do Perfil Profissiográfico Previdenciário – PPP, analise as afirmativas a seguir.\n I. É um documento da vida pregressa do trabalhador.\n II. É uma declaração personalizada para cada segurado.\n III. Pode ser utilizado para a obtenção de aposentadoria especial.\n Está correto o que se afirma em',
    alternatives: [
      '(A) I, somente.',
      '(B) II, somente.',
      '(C) III, somente.',
      '(D) II e III, somente.',
      '(E) I, II e III.',
    ],
    answer: 'E',
    tip: '',
  },
  {
    id: 32,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'Análise de riscos',
    question:
      'A respeito de técnicas e ferramentas de gerenciamento de riscos, analise as afirmativas a seguir.\n I. HAZOP é uma metodologia utilizada no levantamento de problemas em processos industriais.\n II. HAZOP é um procedimento essencialmente quantitativo.\n III. HAZOP não se aplica na identificação de situações perigosas.\n Está correto o que se afirma em',
    alternatives: [
      '(A) I, somente.',
      '(B) II, somente.',
      '(C) III, somente.',
      '(D) II e III, somente.',
      '(E) I, II e III.',
    ],
    answer: 'A',
    tip: '',
  },
  {
    id: 33,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR23',
    question:
      'No combate a um incêndio, que ocorre em uma subestação de energia elétrica, deve ser utilizado o extintor para a Classe',
    alternatives: ['(A) A', '(B) B.', '(C) C.', '(D) D.', '(E) E.'],
    answer: 'C',
    tip: 'Classe A = Materiais combustíveis sólidos (Extintor mais recomendado Água Pressurizada-AP pois resfria e abafa), \n Classe B = Materiais combustíveis líquidos (Extintor mais recomendado Espuma pois abafa o fogo fazendo uma camada entre o líquido e o ar), \n Classe C = Ignição elétrica (Extintor mais recomendado é o de CO2 pois retira o comburuente/oxigênio sem muitos danos aos equipamentos), \n Classe D = Metais Pirofóricos (Extintor mais recomendado é o de pó químico).',
  },
  {
    id: 34,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR5',
    question:
      'Assinale a opção que apresenta a composição e o tempo de mandato da Comissão Interna de Prevenção de Acidentes – CIPA.',
    alternatives: [
      '(A) Representantes dos empregados e mandato de um ano, sem direito à reeleição.',
      '(B) Representantes dos empregados e mandato de um ano, com direito a uma reeleição.',
      '(C) Representantes do empregador e dos empregados e mandato de um ano, sem direito à reeleição.',
      '(D) Representantes do empregador e dos empregados e mandato de dois anos, sem direito à reeleição.',
      '(E) Representantes do empregador e dos empregados e mandato de um ano, com direito a uma reeleição.',
    ],
    answer: 'E',
    tip: '',
  },
  {
    id: 35,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR15',
    question:
      'O ruído é um fator de risco presente no cotidiano e é uma preocupação das atividades de trabalho. A tabela a seguir apresenta o limite máximo de tempo e o tempo real de exposição para cada fonte de ruído.\nFontes de Ruído        Limite Máximo de exposição-horas              Tempo real exposição-horas\n           A                                                      12                                                                  3\n           B                                                      10                                                                  4\n           C                                                       8                                                                   2\nA dosagem de ruído e a tolerância são, respectivamente, de',
    alternatives: [
      '(A) 10,50 e está acima do limite tolerável.',
      '(B) 4,00 e está acima do limite tolerável.',
      '(C) 3,33 e está acima do limite tolerável.',
      '(D) 0,90 e está abaixo do limite tolerável.',
      '(E) 0,30 e está abaixo do limite tolerável.',
    ],
    answer: 'D',
    tip: 'Dose = 3/12 + 4/10 + 2/8 = 1/4 + 2/5 + ¼ = 2/4 + 2/5 = 18/20 =0,9',
  },
  {
    id: 36,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR15',
    question:
      'Em uma indústria, as medições de temperatura de bulbo úmido natural e temperatura de globo são, respectivamente, iguais a 30 °C e 40 °C e o ambiente da indústria é interno, sem carga solar.\n Sabendo-se que o Índice de Bulbo Úmido Termômetro de Globo (IBUTG) avalia a exposição ao calor, o seu valor, em °C, é igual a',
    alternatives: ['(A) 31.', '(B) 33.', '(C) 36.', '(D) 38.', '(E) 39.'],
    answer: 'B',
    tip: 'IBUTG int= Tbu x0,7 + Tg x 0,3 = 30 x 0,7 + 40 x 0,3 = 21 + 12 = 33 ºC ',
  },
  {
    id: 37,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR5',
    question:
      'Os riscos químico e ergonômico são apresentados no mapa de risco nas cores',
    alternatives: [
      '(A) verde e azul.',
      '(B) azul e amarelo.',
      '(C) marrom e verde.',
      '(D) amarelo e marrom.',
      '(E) vermelho e amarelo.',
    ],
    answer: 'E',
    tip: '',
  },
  {
    id: 38,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR10',
    question:
      'Nas intervenções em instalações elétricas devem ser adotadas medidas preventivas de controle do risco elétrico.\n Em relação à segurança em instalações e serviços em eletricidade, assinale a afirmativa correta.',
    alternatives: [
      '(A) As empresas estão obrigadas a atualizar as instalações elétricas anualmente.',
      '(B) O Prontuário de Instalações Elétricas é dispensável para potências abaixo de 1 MVA.',
      '(C) As concessionárias locais devem ser notificadas por ocasião de intervenção que envolva perigo.',
      '(D) Nos serviços em instalações elétricas devem ser previstas e adotadas, prioritariamente, medidas de proteção coletivas.',
      '(E) As medidas de controle na área elétrica devem ser isoladas das demais iniciativas da empresa, dadas as suas particularidades.',
    ],
    answer: 'D',
    tip: '',
  },
  {
    id: 39,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'Análise de riscos',
    question:
      'A higiene ocupacional é um conjunto de ações que visa a preservar a saúde do trabalhador em seu ambiente de trabalho.\n A esse respeito, analise as afirmativas a seguir.\n I. Estimar o grau de criticidade do risco é uma fonte de identificação de riscos.\n II. Inventariar as máquinas é uma forma de identificação de riscos.\n III. Verificar os possíveis danos para a saúde é uma forma de identificação os riscos.\n Está correto o que se afirma em',
    alternatives: [
      '(A) I, somente.',
      '(B) II, somente.',
      '(C) III, somente.',
      '(D) II e III, somente.',
      '(E) I, II e III.',
    ],
    answer: 'B',
    tip: '',
  },
  {
    id: 9005,
    institute: 'FGV',
    level: 'superior',
    profession: 'Engenharia',
    concurso: 'IMBEL',
    year: 2021,
    subject: 'NR9',
    question:
      'Os empregadores têm obrigatoriedade de elaborar e implantar o Programa de Prevenção de Riscos Ambientais – PPRA, que deverá conter como elemento estruturante',
    alternatives: [
      '(A) a exposição dos riscos aos trabalhadores.',
      '(B) a identificação e o reconhecimentos dos riscos.',
      '(C) a implantação de medidas de controle no trabalho.',
      '(D) o monitoramento dos riscos envolvidos no trabalho.',
      '(E) o planejamento anual com metas, prioridades e cronograma.',
    ],
    answer: 'E',
    tip: 'Verificar se ainda está em vigor',
  },
];
